### ISSUE TITLE
Invalid printf format in iolatency/cachestat

### ISSUE THREAD

**Issue by evgkrsk** [brendangregg/perf-tools#30]
``` bash
[root@thinkpad ~]# iolatency 1 2
Tracing block I/O. Output every 1 seconds.

  >=(ms) .. <(ms)   : I/O      |Distribution                          |
       0 -> 1       : 0        |                                      |

  >=(ms) .. <(ms)   : I/O      |Distribution                          |
       0 -> 1       : 0        |                                      |

Ending tracing...
[root@thinkpad ~]# iolatency -T 1 2
Tracing block I/O. Output every 1 seconds.
/usr/bin/iolatency: line 204: printf: `(': invalid format character
/usr/bin/iolatency: line 204: printf: `(': invalid format character

Ending tracing...
[root@thinkpad ~]# which printf
/usr/bin/printf
```

**Comment by scotte** [comment]
You don't have, for example, /bin/bash linked to /bin/zsh (which has a printf built-in that doesn't know about %()T expressions), do you? The "invalid format character" message exactly what zsh displays (and different than, say, the dash built-in which is "invalid conversion specification"). Otherwise I'd guess your /usr/bin/printf, for whatever reason, doesn't support those expressions, perhaps it's too old?

**Comment by evgkrsk** [comment]
I have zsh as root shell, but it is not linked to /bin/bash.

/usr/bin/printf is from coreutils-8.27.0.23.f4570

**Comment by scotte** [comment]
Ah, so the "%()T" expression requires using a bash built-in, not /usr/bin/printf (which only supports whatever the C printf() function does). So - I'm going to guess either your bash doesn't support this expression (looks like this has been in bash since 4.2 - circa 2011) or somehow another printf implementation is being used here (zsh shows the same error message you have, /usr/bin/printf does not). Does your "bash" manpage show a section about %(datefmt)T ? Does printf "%(%H)T\n" (run from bash) display the current hour?

**Comment by evgkrsk** [comment]
You are right:
```
evg@thinkpad ~ $exec bash
bash-3.2$ printf "%(%H)T\n"
bash: printf: `(': invalid format character
bash-3.2$ 
```
but:
```
root@thinkpad ~ #bash4 /usr/bin/iolatency -T 1 2
Tracing block I/O. Output every 1 seconds.

09:39:41:
  >=(ms) .. <(ms)   : I/O      |Distribution                          |
       0 -> 1       : 0        |                                      |

09:39:42:
  >=(ms) .. <(ms)   : I/O      |Distribution                          |
       0 -> 1       : 5        |######################################|

Ending tracing...
root@thinkpad ~ #
```

seems like I need to migrate /bin/bash from 3.2 to 4.2+

Thanks for support!

**Comment by scotte** [comment]
Excellent! Glad that's is solved for you and thanks for following up.
